version: 2
jobs:
  test-simple:
    docker:
      - image: circleci/golang:1.14

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: go test -v ./...
  test-docker:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: |
          make test
